apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: kube-ops
  labels:
    pv: postgresql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # 本地存储
  # hostPath:
  #   path: "/data/svr/pgdb"
  nfs:
    path: /data/nfsdata
    server: 10.10.1.1
