apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: kube-ops
  labels:
    pv: redis-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/nfsdata
    server: 10.10.1.1
